<?php

use app\enums\Type_Module_Sub_Module;
use app\enums\Type_Module;
use app\enums\Type_Role;

return [
    [
        'route' => '/stock/item',
        'label' => 'Item',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/item-group',
        'label' => 'Item Group',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/item-warehouse',
        'label' => 'Item Warehouse',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/item-price',
        'label' => 'Item Price',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/item-bundle',
        'label' => 'Item Bundle',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/brand',
        'label' => 'Brand',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/delivery-note',
        'label' => 'Delivery Note',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/item-uom',
        'label' => 'Item Unit of Measure',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/purchase-receipt',
        'label' => 'Purchase Receipt',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/stock-settings',
        'label' => 'Settings',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/stock-entry',
        'label' => 'Stock Entry',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
    [
        'route' => '/stock/warehouse',
        'label' => 'Warehouse',
        'icon' => 'user',
        'iconPath' => null,
        'iconColor' => 'yellow',
        'group' => Type_Module::Stock,
        'visible' => true, // Yii::$app->user->can(Type_Role::Stockkeeper),
    ],
];
?>